databases:
  - name: chuks-kitchen-db
    databaseName: chuks_kitchen
    user: chuks
    plan: free

services:
  - type: web
    name: chuks-kitchen-api
    runtime: docker
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: DB_URL
        fromDatabase:
          name: chuks-kitchen-db
          property: connectionString
      - key: SECRET_KEY
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: ALLOWED_ORIGINS
        sync: false
